// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmzbboausdhmrwigzkho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtemJib2F1c2RobXJ3aWd6a2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzQ4OTUsImV4cCI6MjA2NjExMDg5NX0.tLSKNtp3vPE6QfFGIOyb9OUV9dLiw5mrhUUPZRUM9BY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);